services:
  postgres:
    image: postgres:16.4
    container_name: my-postgres
    restart: unless-stopped
    ports:
      - '5434:5432'
    env_file:
      - .env
    volumes:
      - ./.sst/storage/postgres:/var/lib/postgresql/data
